// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: termemul

#ifndef _TERMEMUL_UI_H
#define _TERMEMUL_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_TerminalContainer;
extern lv_obj_t * ui_TerminalTextArea;
extern lv_obj_t * ui_ConfigContainer;
extern lv_obj_t * ui_TitleLabel;
extern lv_obj_t * ui_Brightness_Container;
extern lv_obj_t * ui_BrightnessLabel;
extern lv_obj_t * ui_BrightnessSlider;
void ui_event_ShowKbdButton(lv_event_t * e);
extern lv_obj_t * ui_ShowKbdButton;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Keyboard;
extern lv_obj_t * ui____initial_actions0;





void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
