// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: termemul

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TerminalContainer = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_TerminalContainer);
    lv_obj_set_width(ui_TerminalContainer, 500);
    lv_obj_set_height(ui_TerminalContainer, lv_pct(100));
    lv_obj_set_align(ui_TerminalContainer, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_TerminalContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TerminalTextArea = lv_textarea_create(ui_TerminalContainer);
    lv_obj_set_width(ui_TerminalTextArea, lv_pct(100));
    lv_obj_set_height(ui_TerminalTextArea, lv_pct(100));
    lv_obj_set_align(ui_TerminalTextArea, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TerminalTextArea,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE);     /// Flags
    lv_obj_set_style_radius(ui_TerminalTextArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_TerminalTextArea, lv_color_hex(0xFFFFFF), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TerminalTextArea, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_TerminalTextArea, LV_BORDER_SIDE_NONE, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_ConfigContainer = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_ConfigContainer);
    lv_obj_set_width(ui_ConfigContainer, 300);
    lv_obj_set_height(ui_ConfigContainer, lv_pct(100));
    lv_obj_set_align(ui_ConfigContainer, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_ConfigContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TitleLabel = lv_label_create(ui_ConfigContainer);
    lv_obj_set_width(ui_TitleLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TitleLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TitleLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_TitleLabel, "Terminator Emulator 2000");
    lv_obj_set_style_pad_left(ui_TitleLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TitleLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TitleLabel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TitleLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Brightness_Container = lv_obj_create(ui_ConfigContainer);
    lv_obj_remove_style_all(ui_Brightness_Container);
    lv_obj_set_height(ui_Brightness_Container, 40);
    lv_obj_set_width(ui_Brightness_Container, lv_pct(100));
    lv_obj_set_x(ui_Brightness_Container, 0);
    lv_obj_set_y(ui_Brightness_Container, 50);
    lv_obj_set_align(ui_Brightness_Container, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Brightness_Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BrightnessLabel = lv_label_create(ui_Brightness_Container);
    lv_obj_set_width(ui_BrightnessLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BrightnessLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BrightnessLabel, -84);
    lv_obj_set_y(ui_BrightnessLabel, 0);
    lv_obj_set_align(ui_BrightnessLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BrightnessLabel, "0%");
    lv_obj_set_style_text_align(ui_BrightnessLabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrightnessSlider = lv_slider_create(ui_Brightness_Container);
    lv_slider_set_value(ui_BrightnessSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_BrightnessSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_BrightnessSlider, 0,
                                                                                                     LV_ANIM_OFF);
    lv_obj_set_width(ui_BrightnessSlider, 165);
    lv_obj_set_height(ui_BrightnessSlider, 10);
    lv_obj_set_x(ui_BrightnessSlider, 41);
    lv_obj_set_y(ui_BrightnessSlider, 0);
    lv_obj_set_align(ui_BrightnessSlider, LV_ALIGN_CENTER);


    ui_ShowKbdButton = lv_btn_create(ui_ConfigContainer);
    lv_obj_set_width(ui_ShowKbdButton, LV_SIZE_CONTENT);   /// 108
    lv_obj_set_height(ui_ShowKbdButton, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_ShowKbdButton, 0);
    lv_obj_set_y(ui_ShowKbdButton, 400);
    lv_obj_set_align(ui_ShowKbdButton, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_ShowKbdButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ShowKbdButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_ShowKbdButton);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Show KBD");

    ui_Keyboard = lv_keyboard_create(ui_Screen1);
    lv_obj_set_width(ui_Keyboard, 600);
    lv_obj_set_height(ui_Keyboard, 240);
    lv_obj_set_align(ui_Keyboard, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Keyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Keyboard, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE);     /// Flags
    lv_obj_set_style_outline_width(ui_Keyboard, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Keyboard, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ShowKbdButton, ui_event_ShowKbdButton, LV_EVENT_ALL, NULL);

}
